#version 430

struct DataPoint
{
    vec4 pos;
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) restrict writeonly buffer data_point_buffer
{
    DataPoint data_point[];
};

uniform int work_group_offset = 0;
uniform float value;


void write(highp uint index, vec4 pos)
{
    data_point[index].pos = pos;
}

void main() {
    highp uint index = gl_WorkGroupID.x + work_group_offset;

    vec4 data = vec4(value, value, value, value);
    write(index, data);
}
